version: '3.3'
services:
  tainacan:
    image: tainacan/tainacan
    container_name: integracao_tnc_tainacan
    ports:
      - "6076:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: taincan_user
      WORDPRESS_DB_PASSWORD: jtr%6i
      WORDPRESS_DB_NAME: tainacan
    volumes:
    - ./tainacan/html:/var/www/html/
    - ./tainacan/html/wp-content/themes:/var/www/html/wp-content/themes/
    - ./tainacan/html/wp-content/plugins:/var/www/html/wp-content/plugins/
    - ./tainacan/html/wp-content/uploads:/var/www/html/wp-content/uploads/

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Er$$8*uhy#
      MYSQL_DATABASE: tainacan
      MYSQL_USER: taincan_user
      MYSQL_PASSWORD: jtr%6i
    volumes:
    - ./dbdata:/var/lib/mysql
    - ./init.d/mysql:/docker-entrypoint-initdb.d

  elasticsearch:
    container_name: integracao_tnc_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.watermark.flood_stage=99%
      - cluster.routing.allocation.disk.watermark.high=98%
      # - xpack.security.enabled=true
    deploy:
      resources:
        limits:
          memory: 6144M
    volumes:
      - ./esdata:/usr/share/elasticsearch/data


  logstash:
    container_name: integracao_tnc_logstash
    # image: docker.elastic.co/logstash/logstash:7.9.0
    build:
      context: .
      dockerfile: ./Dockerfile/logstash
    environment:
       LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    volumes:
      - ./logstash/data:/usr/share/logstash/data
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/plugins:/plugins
      - type: volume
        source: share_logstash
        target: /usr/share/logstash
        volume:
          nocopy: false
    depends_on:
      - elasticsearch

  filebeat:
    container_name: integracao_tnc_filebeat
    hostname: filebeat
    user: root
    environment:
      - BEAT_STRICT_PERMS=false
    image: docker.elastic.co/beats/filebeat:7.9.0
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/inputs.d:/usr/share/filebeat/inputs.d
      - ./filebeat/fbdata:/usr/share/filebeat/data/
    restart: on-failure
    depends_on: 
      - elasticsearch
      - logstash
 
  kibana:
    container_name: integracao_tnc_kibana
    image: docker.elastic.co/kibana/kibana:7.9.0
    ports: 
      - 6601:5601
    #volumes:
    #  - ./kibana/config:/usr/share/kibana/config/
    depends_on: 
      - elasticsearch

volumes:
  share_logstash:
    driver: local
    driver_opts:
      type: none
      device: /home/medialab/tainacan_docker/tainacan-integracao/logstash/logstash
      o: bind
