version: '3.3'
services:
  elasticsearch:
    container_name: elasticsearch_integracao
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.watermark.flood_stage=99%
      - cluster.routing.allocation.disk.watermark.high=98%
      - xpack.security.enabled=true
    volumes:
      - esdata_integracao:/usr/share/elasticsearch/data

  logstash:
    container_name: logstash_integracao
    image: docker.elastic.co/logstash/logstash:7.9.0
    ports:
      - 5000:5000
    environment:
       LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
       LS_OPTS: "--config.reload.automatic --config.reload.interval 5s"
    volumes:
      - ./config/logstash/pipeline:/usr/share/logstash/pipeline
      - ./config/logstash/scripts:/scripts
      - type: volume
        source: share_logstash
        target: /usr/share/logstash
        volume:
          nocopy: false

  filebeat:
    container_name: filebeat_integracao
    hostname: filebeat
    user: root
    environment:
      - BEAT_STRICT_PERMS=false
    image: docker.elastic.co/beats/filebeat:7.9.0
    volumes:
      - ./config/beats/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./config/beats/filebeat/inputs.d:/usr/share/filebeat/inputs.d
      - fbdata:/usr/share/filebeat/data/
    restart: on-failure
 
  kibana:
    container_name: kibana_integracao
    image: docker.elastic.co/kibana/kibana:7.9.0
    ports: 
      - 5601:5601
    depends_on: 
      - elasticsearch

volumes:
  esdata_integracao:
  fbdata:
  logstashdata:
  share_logstash:
    driver: local
    driver_opts:
      type: none
      device: /home/vinicius/Development/tainacan/tainacan-elk/share_logstash
      o: bind

#https://datastudio.google.com/reporting/469f706e-1574-4826-8fc3-39fd932a4255?s=rKoNxRs9FIw
#sudo docker network connect dev_default filebeat_integracao
