- type: httpjson
  http_method: GET
  interval: 3600s
  #interval: 10s
  url: https://museudoouro.acervos.museus.gov.br/wp-json/tainacan/v2/collection/3583/items?perpage=100&paged=1
  json_objects_array: "items"
  #pagination:
    #extra_body_content:
    #  perpage: 1
    #id_field: paged
    #req_field: paged
    #header:
    #  field_name: x-wp-totalpages
    #  regex_pattern: "{d}"
    #url: https://rcteste.tainacan.org/wp-json/tainacan/v2/collection/19592/items
  processors:
  - decode_json_fields:
      fields: [message]
      target: json
  - convert:
      mode: "rename"
      fields:
        - {from: "json.title",                                        to: "payload.titulo"}
        - {from: "json.description",                                  to: "payload.descricao"}
        - {from: "json.collection_id",                                to: "payload.colecaoId"}
        - {from: "json.metadata.classificacao-3.value_as_string",     to: "payload.classificacao"}
        - {from: "json.metadata.material-tecnica-3.value_as_string",  to: "payload.material"}
        - {from: "json.metadata.numero-de-registro-3.value_as_string",to: "payload.numeroRegistro"}
      ignore_missing: true
      fail_on_error: false
  - drop_fields:
      fields: ["message", "json"]
  - add_fields:
      target: payload
      fields:
        instalacao: "museu do ouro"

#x-wp-total #total de itens
    #x-wp-totalpages #total de pagina