- type: httpjson
  http_method: GET
  interval: 3600s
  url: https://rcteste.tainacan.org/wp-json/tainacan/v2/collection/21399/items/?perpage=1&order=DESC&orderby=date&exposer=json-flat&mapper=inbcm-ibram
  #json_objects_array: "items"
  pagination:
    enabled: true
    extra_body_content:
      perpage: 1
    id_field: pagination.next_page
    req_field: paged
    url: https://rcteste.tainacan.org/wp-json/tainacan/v2/collection/21399/items/?perpage=1&order=DESC&orderby=date&exposer=json-flat&mapper=inbcm-ibram
  
  processors:
  - decode_json_fields:
      fields: [message]
      target: json
  - convert:
      mode: "rename"
      fields:
        - {from: "json.pagination",                                       to: "payload.pagination"}
        - {from: "json.data.titulo",                                      to: "payload.titulo"}
        - {from: "dimensoes",                                             to: "payload.descricao"}
#        - {from: "json.collection_id",                                to: "payload.colecaoId"}
#        - {from: "json.metadata.extra-metadata-4.value_as_string",    to: "payload.classificacao"}
#        - {from: "json.metadata.numeric-type.value_as_string",        to: "payload.material"}
#        #- {from: "json.metadata.text-type.value_as_string",           to: "payload.numeroRegistro"}
      ignore_missing: true
      fail_on_error: false
#  - drop_fields:
#      fields: ["message", "json"]
  - add_fields:
      target: payload
      fields:
        instalacao: "RC-TESTE"